///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Accounts;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json;
using SDK.Models.Shared;
using SDK.Models.Accounts;
using SDK.Utils;

public interface IAccountsSDK
{
    Task<ListUsersResponse> ListUsersAsync();
}

public class AccountsSDK: IAccountsSDK
{

    private const string language = "csharp";
    private const string sdkVersion = "0.0.1";
    private const string sdkGenVersion = "internal";
    public Uri ServerUrl { get { return _defaultClient.BaseAddress; } }
    private HttpClient _defaultClient;
    private HttpClient _securityClient;

    public AccountsSDK(HttpClient defaultClient, HttpClient securityClient)
    {
        _defaultClient = defaultClient;
        _securityClient = securityClient;
    }

    
    public async Task<ListUsersResponse> ListUsersAsync()
    {
        string baseUrl = "";
        var message = new HttpRequestMessage(HttpMethod.Get, "/accounts");
        var httpResponseMessage = await _defaultClient.SendAsync(message);
        var response = new ListUsersResponse
        {
            StatusCode = (int)httpResponseMessage.StatusCode,
            ContentType = httpResponseMessage.Content.Headers.ContentType?.MediaType,
            RawResponse = httpResponseMessage
        };
        if((response.StatusCode == 200))
        {
            if(Utilities.IsContentTypeMatch("*/*",response.ContentType))
            {
                // */*
                throw new NotImplementedException();
            }
            return response;
        }
        if((response.StatusCode == 401))
        {
            return response;
        }
        return response;
    }

    
}