///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.User;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json;
using SDK.Models.Shared;
using SDK.Models.User;
using SDK.Utils;

public interface IUserSDK
{
    Task<LoginResponse> LoginAsync(LoginApplicationJSON request);
    Task<MeResponse> MeAsync();
}

public class UserSDK: IUserSDK
{

    private const string language = "csharp";
    private const string sdkVersion = "0.0.1";
    private const string sdkGenVersion = "internal";
    public Uri ServerUrl { get { return _defaultClient.BaseAddress; } }
    private HttpClient _defaultClient;
    private HttpClient _securityClient;

    public UserSDK(HttpClient defaultClient, HttpClient securityClient)
    {
        _defaultClient = defaultClient;
        _securityClient = securityClient;
    }

    
    public async Task<LoginResponse> LoginAsync(LoginApplicationJSON request)
    {
        string baseUrl = "";
        var message = LoginApplicationJSON.BuildHttpRequestMessage("login", request);
        var httpResponseMessage = await _defaultClient.SendAsync(message);
        var response = new LoginResponse
        {
            StatusCode = (int)httpResponseMessage.StatusCode,
            ContentType = httpResponseMessage.Content.Headers.ContentType?.MediaType,
            RawResponse = httpResponseMessage
        };
        if((response.StatusCode == 200))
        {
            if(Utilities.IsContentTypeMatch("*/*",response.ContentType))
            {
                // */*
                throw new NotImplementedException();
            }
            return response;
        }
        if((response.StatusCode == 401))
        {
            return response;
        }
        return response;
    }

    
    public async Task<MeResponse> MeAsync()
    {
        string baseUrl = "";
        var message = new HttpRequestMessage(HttpMethod.Get, "/me");
        var httpResponseMessage = await _defaultClient.SendAsync(message);
        var response = new MeResponse
        {
            StatusCode = (int)httpResponseMessage.StatusCode,
            ContentType = httpResponseMessage.Content.Headers.ContentType?.MediaType,
            RawResponse = httpResponseMessage
        };
        if((response.StatusCode == 200))
        {
            if(Utilities.IsContentTypeMatch("*/*",response.ContentType))
            {
                // */*
                throw new NotImplementedException();
            }
            return response;
        }
        if((response.StatusCode == 401))
        {
            return response;
        }
        return response;
    }

    
}