///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.User;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class LoginApplicationJSON
{
    [JsonProperty("email")]
    public string Email { get; set; }
    
    [JsonProperty("password")]
    public string Password { get; set; }
    
    internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, LoginApplicationJSON value)
    {
        if("login" == operationId)
        {
            var message = new HttpRequestMessage(HttpMethod.Post, "/auths");

            string json = JsonConvert.SerializeObject(value);
            message.Content = new StringContent(json, Encoding.UTF8, "application/json");
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [LoginApplicationJSON]");
    }
}
