///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class Account
{
    [JsonProperty("account_users")]
    public IEnumerable<string> AccountUsers { get; set; }
    
    [JsonProperty("created_at")]
    public string CreatedAt { get; set; }
    
    [JsonProperty("id")]
    public float Id { get; set; }
    
    [JsonProperty("name")]
    public string Name { get; set; }
    
    [JsonProperty("owner_id")]
    public float OwnerId { get; set; }
    
    [JsonProperty("personal")]
    public bool Personal { get; set; }
    
    [JsonProperty("updated_at")]
    public string UpdatedAt { get; set; }
    
}
