///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class Person
{
    [JsonProperty("birth_date")]
    public string BirthDate { get; set; }
    
    [JsonProperty("birth_year")]
    public float BirthYear { get; set; }
    
    [JsonProperty("certifications")]
    public IEnumerable<string> Certifications { get; set; }
    
    [JsonProperty("education")]
    public IEnumerable<string> Education { get; set; }
    
    [JsonProperty("emails")]
    public IEnumerable<string> Emails { get; set; }
    
    [JsonProperty("experience")]
    public IEnumerable<string> Experience { get; set; }
    
    [JsonProperty("facebook_id")]
    public string FacebookId { get; set; }
    
    [JsonProperty("facebook_url")]
    public string FacebookUrl { get; set; }
    
    [JsonProperty("facebook_username")]
    public string FacebookUsername { get; set; }
    
    [JsonProperty("first_name")]
    public string FirstName { get; set; }
    
    [JsonProperty("full_name")]
    public string FullName { get; set; }
    
    [JsonProperty("gender")]
    public string Gender { get; set; }
    
    [JsonProperty("github_url")]
    public string GithubUrl { get; set; }
    
    [JsonProperty("github_username")]
    public string GithubUsername { get; set; }
    
    [JsonProperty("id")]
    public float Id { get; set; }
    
    [JsonProperty("industry")]
    public string Industry { get; set; }
    
    [JsonProperty("inferred_salary")]
    public string InferredSalary { get; set; }
    
    [JsonProperty("inferred_years_experience")]
    public float InferredYearsExperience { get; set; }
    
    [JsonProperty("interests")]
    public IEnumerable<string> Interests { get; set; }
    
    [JsonProperty("job_company_facebook_url")]
    public string JobCompanyFacebookUrl { get; set; }
    
    [JsonProperty("job_company_founded")]
    public string JobCompanyFounded { get; set; }
    
    [JsonProperty("job_company_id")]
    public string JobCompanyId { get; set; }
    
    [JsonProperty("job_company_industry")]
    public string JobCompanyIndustry { get; set; }
    
    [JsonProperty("job_company_linkedin_id")]
    public string JobCompanyLinkedinId { get; set; }
    
    [JsonProperty("job_company_linkedin_url")]
    public string JobCompanyLinkedinUrl { get; set; }
    
    [JsonProperty("job_company_location_address_line_2")]
    public string JobCompanyLocationAddressLine2 { get; set; }
    
    [JsonProperty("job_company_location_continent")]
    public string JobCompanyLocationContinent { get; set; }
    
    [JsonProperty("job_company_location_country")]
    public string JobCompanyLocationCountry { get; set; }
    
    [JsonProperty("job_company_location_geo")]
    public string JobCompanyLocationGeo { get; set; }
    
    [JsonProperty("job_company_location_locality")]
    public string JobCompanyLocationLocality { get; set; }
    
    [JsonProperty("job_company_location_metro")]
    public string JobCompanyLocationMetro { get; set; }
    
    [JsonProperty("job_company_location_name")]
    public string JobCompanyLocationName { get; set; }
    
    [JsonProperty("job_company_location_postal_code")]
    public string JobCompanyLocationPostalCode { get; set; }
    
    [JsonProperty("job_company_location_region")]
    public string JobCompanyLocationRegion { get; set; }
    
    [JsonProperty("job_company_location_street_address")]
    public string JobCompanyLocationStreetAddress { get; set; }
    
    [JsonProperty("job_company_name")]
    public string JobCompanyName { get; set; }
    
    [JsonProperty("job_company_size")]
    public string JobCompanySize { get; set; }
    
    [JsonProperty("job_company_twitter_url")]
    public string JobCompanyTwitterUrl { get; set; }
    
    [JsonProperty("job_company_website")]
    public string JobCompanyWebsite { get; set; }
    
    [JsonProperty("job_last_updated")]
    public string JobLastUpdated { get; set; }
    
    [JsonProperty("job_start_date")]
    public string JobStartDate { get; set; }
    
    [JsonProperty("job_summary")]
    public string JobSummary { get; set; }
    
    [JsonProperty("job_title")]
    public string JobTitle { get; set; }
    
    [JsonProperty("job_title_levels")]
    public IEnumerable<string> JobTitleLevels { get; set; }
    
    [JsonProperty("job_title_role")]
    public string JobTitleRole { get; set; }
    
    [JsonProperty("job_title_sub_role")]
    public string JobTitleSubRole { get; set; }
    
    [JsonProperty("languages")]
    public IEnumerable<string> Languages { get; set; }
    
    [JsonProperty("last_name")]
    public string LastName { get; set; }
    
    [JsonProperty("linkedin_connections")]
    public float LinkedinConnections { get; set; }
    
    [JsonProperty("linkedin_id")]
    public float LinkedinId { get; set; }
    
    [JsonProperty("linkedin_url")]
    public string LinkedinUrl { get; set; }
    
    [JsonProperty("linkedin_username")]
    public string LinkedinUsername { get; set; }
    
    [JsonProperty("location_address_line_two")]
    public string LocationAddressLineTwo { get; set; }
    
    [JsonProperty("location_continent")]
    public string LocationContinent { get; set; }
    
    [JsonProperty("location_country")]
    public string LocationCountry { get; set; }
    
    [JsonProperty("location_geo")]
    public IEnumerable<string> LocationGeo { get; set; }
    
    [JsonProperty("location_last_updated")]
    public string LocationLastUpdated { get; set; }
    
    [JsonProperty("location_locality")]
    public string LocationLocality { get; set; }
    
    [JsonProperty("location_metro")]
    public string LocationMetro { get; set; }
    
    [JsonProperty("location_name")]
    public string LocationName { get; set; }
    
    [JsonProperty("location_postal_code")]
    public string LocationPostalCode { get; set; }
    
    [JsonProperty("location_region")]
    public string LocationRegion { get; set; }
    
    [JsonProperty("location_street_address")]
    public string LocationStreetAddress { get; set; }
    
    [JsonProperty("middle_initial")]
    public string MiddleInitial { get; set; }
    
    [JsonProperty("middle_name")]
    public string MiddleName { get; set; }
    
    [JsonProperty("mobile_phone")]
    public string MobilePhone { get; set; }
    
    [JsonProperty("phone_numbers")]
    public IEnumerable<string> PhoneNumbers { get; set; }
    
    [JsonProperty("profiles")]
    public IEnumerable<string> Profiles { get; set; }
    
    [JsonProperty("skills")]
    public IEnumerable<string> Skills { get; set; }
    
    [JsonProperty("street_addresses")]
    public IEnumerable<string> StreetAddresses { get; set; }
    
    [JsonProperty("summary")]
    public string Summary { get; set; }
    
    [JsonProperty("twitter_url")]
    public string TwitterUrl { get; set; }
    
    [JsonProperty("twitter_username")]
    public string TwitterUsername { get; set; }
    
    [JsonProperty("work_email")]
    public string WorkEmail { get; set; }
    
}
