///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Utils;
using System.Collections.Generic;
using System.Net.Http;

internal class FormSerializer
{
    public static HttpContent Serialize(object value) =>
        new StringContent(Utilities.ToString(value));
}
