///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.People;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class EnrichPersonRequest
{
    [JsonProperty("id")]
    public string Id { get; set; }
    
    internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, EnrichPersonRequest value)
    {
        if("enrich_person" == operationId)
        {
            // add path params
            
            var id = PathParamSerializer.Serialize("simple", false, value.Id);
            var message = new HttpRequestMessage(HttpMethod.Get, $"/people/{id}/enrich");
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [EnrichPersonRequest]");
    }
}
